services:
  mysql:
    image: mysql:8.0.34
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=app
      - MYSQL_USER=api
      - MYSQL_PASSWORD=secret